name: CI

on:
  push:
    branches:
      - main  # Thay đổi theo nhánh bạn muốn
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t udagram-frontend ./udagram-frontend
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t reverseproxy ./udagram-reverseproxy

      - name: Tag Docker images
        run: |
          docker tag udagram-frontend nhulh18/udagram-frontend:latest
          docker tag udagram-api-feed nhulh18/udagram-api-feed:latest
          docker tag udagram-api-user nhulh18/udagram-api-user:latest
          docker tag reverseproxy nhulh18/reverseproxy:latest

      - name: Push Docker images
        run: |
          docker push nhulh18/udagram-frontend:latest
          docker push nhulh18/udagram-api-feed:latest
          docker push nhulh18/udagram-api-user:latest
          docker push nhulh18/reverseproxy:latest
